import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
// import JotaiProvider from "@/providers/JotaiProvider";
import { Suspense } from "react";

const sans = Encode_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			{/* <JotaiProvider> */}
			<body className={sans.className}>
				<Suspense>{children}</Suspense>
			</body>
			{/* </JotaiProvider> */}
		</html>
	);
}
